### PR TITLE
Master

### PR DESCRIPTION
**Pull request by barisusakli**

### CODE REVIEW

**Comment by barisusakli** [comment]
Updates the plugin so it works on nbb 0.9.0+.
Fixed a crash if there was no `options.folder` property set in the ACP page
Fixed the api/template so it doesn't display `{config.api_key}` if it was ajaxified to.

**Comment by julianlam** [comment]
Alternatively, if @drlogout is amenable, we can continue the plugin on https://github.com/NodeBB-Community/nodebb-plugin-cloudinary, and grant npm ownership to @barisusakli

**Comment by julianlam** [comment]
Pinging @drlogout  :smile:

**Comment by drlogout** [comment]
Sorry for the long delay.

**Pull request merged**
